version: "3.8"  # Specify a valid Compose version

services:
  app:
    build: .
    container_name: url-shortener-api
    restart: always
    env_file: .env
    ports:
      - "4000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network: {}  # Fix incorrect indentation

volumes:
  mongo-data: {}  # Fix incorrect indentation
